services:
  oracle-db:
    build: .
    container_name: oracle-db
    environment:
      - ORACLE_PWD=oracle
    ports:
      - 1521:1521
    volumes:
      - ./tarea3.sql:/opt/oracle/scripts/startup/tarea3.sql
