ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER prueba IDENTIFIED BY prueba;
GRANT CONNECT, RESOURCE, DBA TO prueba;
ALTER USER prueba QUOTA UNLIMITED ON USERS;

CREATE TABLE prueba.users (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    precio INT 
);

