
CREATE TABLE COMERCIAL (
    DNI CHAR(9), 
    NOMBRE VARCHAR2 (30),
    APELLIDOS VARCHAR (50),
    FECHA_NACIMIENTO DATE,
    BONIFICACION DECIMAL (8,2),
    TITULACION VARCHAR2 (100)
);

CREATE TABLE PROGRAMADOR (
    DNI CHAR(8),
    NOMBRE VARCHAR2 (30),
    APELLIDOS VARCHAR (50),
    FECHA_NACIMIENTO DATE,
    LENGUAJES VARCHAR2(50),
    PUESTO VARCHAR2 (100)
);

CREATE TABLE DEPARTMENTO (
    ID_DEPARTAMENTO NUMBER,
    ID_SUCURSAL NUMBER,
    NOMBRE VARCHAR2 (30),
    DIRECCION VARCHAR2(50)
);

CREATE TABLE SUCURSAL (
    ID_SUCURSAL NUMBER,
    NOMBRE VARCHAR2(30),
    DIRECCION VARCHAR2(50)
);

CREATE TABLE PROYECTOS (
    COD_PROYECTO VARCHAR2(30),
    NOMBRE VARCHAR2 (30),
    ID_DEPARTAMENTO NUMBER,
    ID_SUCURSAL NUMBER
);

CREATE TABLE PROYECTO_CLIENTE (
    COD_PROYECTO VARCHAR2(30),
    ID_CLIENTE NUMBER
);

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER,
    NOMBRE VARCHAR2 (30),
    TELEFONO VARCHAR2 (20),
    DIRECCION VARCHAR2(50),
    EMAIL VARCHAR2 (200)
);


